// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';
import 'package:social_me/main.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt3WD0PADRHPeo8KljGCBuwrVb3iqsXF4',
    appId: '1:601972829668:web:cbea4437b500eba76eabf1',
    messagingSenderId: '601972829668',
    projectId: 'socialme-c7aa4',
    authDomain: 'socialme-c7aa4.firebaseapp.com',
    storageBucket: 'socialme-c7aa4.appspot.com',
    measurementId: 'G-SJPVCCHYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBagTucMqS5Gt386EJZCNRWkfzD_Grtjrw',
    appId: '1:601972829668:android:eaea169f8f0b0edb6eabf1',
    messagingSenderId: '601972829668',
    projectId: 'socialme-c7aa4',
    storageBucket: 'socialme-c7aa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbe_2_9KKRGtrp5zjsJnjFoE5slSntdrE',
    appId: '1:601972829668:ios:7fb4a3235d5510af6eabf1',
    messagingSenderId: '601972829668',
    projectId: 'socialme-c7aa4',
    storageBucket: 'socialme-c7aa4.appspot.com',
    iosBundleId: 'com.example.socialMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbe_2_9KKRGtrp5zjsJnjFoE5slSntdrE',
    appId: '1:601972829668:ios:7fb4a3235d5510af6eabf1',
    messagingSenderId: '601972829668',
    projectId: 'socialme-c7aa4',
    storageBucket: 'socialme-c7aa4.appspot.com',
    iosBundleId: 'com.example.socialMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt3WD0PADRHPeo8KljGCBuwrVb3iqsXF4',
    appId: '1:601972829668:web:419132f9ab69c3336eabf1',
    messagingSenderId: '601972829668',
    projectId: 'socialme-c7aa4',
    authDomain: 'socialme-c7aa4.firebaseapp.com',
    storageBucket: 'socialme-c7aa4.appspot.com',
    measurementId: 'G-TF7YDR3D4E',
  );
}
