// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';
import 'package:social_me/main.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSlOF-lda8vl21FLShPgYvK70IQ_l42aM',
    appId: '1:502891628679:web:6c8dd3a6c91762d93e1022',
    messagingSenderId: '502891628679',
    projectId: 'social-me-1baf9',
    authDomain: 'social-me-1baf9.firebaseapp.com',
    storageBucket: 'social-me-1baf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPqJTQKkn5aRk3gewmAIxVxtEj-gPoxc',
    appId: '1:502891628679:android:ace36c8dfa2356603e1022',
    messagingSenderId: '502891628679',
    projectId: 'social-me-1baf9',
    storageBucket: 'social-me-1baf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjePXhJlN8aNDjyEYK3h96-47K2U4lNFw',
    appId: '1:502891628679:ios:d55434a597f3a50d3e1022',
    messagingSenderId: '502891628679',
    projectId: 'social-me-1baf9',
    storageBucket: 'social-me-1baf9.appspot.com',
    iosBundleId: 'com.example.socialMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjePXhJlN8aNDjyEYK3h96-47K2U4lNFw',
    appId: '1:502891628679:ios:d55434a597f3a50d3e1022',
    messagingSenderId: '502891628679',
    projectId: 'social-me-1baf9',
    storageBucket: 'social-me-1baf9.appspot.com',
    iosBundleId: 'com.example.socialMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSlOF-lda8vl21FLShPgYvK70IQ_l42aM',
    appId: '1:502891628679:web:f04634a70e9af4e63e1022',
    messagingSenderId: '502891628679',
    projectId: 'social-me-1baf9',
    authDomain: 'social-me-1baf9.firebaseapp.com',
    storageBucket: 'social-me-1baf9.appspot.com',
  );

}